<?php
declare(strict_types=1);
require_once __DIR__.'/../src/Schema/LocationData.php';
require __DIR__.'/../src/Schema/JobFields.php';
require __DIR__.'/../src/Schema/JobMapper.php';
require __DIR__.'/../src/Schema/EntityMapper.php';
$check = static function (bool $ok, string $label): void { if (!$ok) { throw new RuntimeException($label); } };
$mapper = new VHUG\SchemaManagerBundle\Schema\JobMapper();
$now = 1800000000;
$record = ['schemaIdentity'=>'https://example.org/#job-1','date'=>$now-86400];
$defaults = ['schemaJobEmployment'=>serialize(['FULL_TIME']), 'schemaJobCity'=>'Stuttgart', 'schemaJobCountry'=>'DE'];
$employer = ['@id'=>'https://example.org/#company'];
$map = static fn (array $changes = [], array $archive = []) => $mapper->map(array_replace($record,$changes),array_replace($defaults,$archive),$employer,'https://example.org/job/a','de','Creative Director','Public job description',$now);
$job=$map();
$check($job['@type']==='JobPosting' && $job['hiringOrganization']===$employer,'Job type and reference');
$check($job['employmentType']===['FULL_TIME'] && $job['jobLocation']['address']['addressLocality']==='Stuttgart','Archive defaults');
$check($map(['schemaJobCity'=>'Berlin'])['jobLocation']['address']['addressLocality']==='Berlin','Record override');
$check($map(['schemaJobEmployment'=>serialize(['PART_TIME','CONTRACTOR'])])['employmentType']===['PART_TIME','CONTRACTOR'],'Multiple employment types');
$check($map(['schemaJobValidThrough'=>$now])===null,'Expired job excluded');
$check(isset($map(['schemaJobValidThrough'=>$now+100])['validThrough']),'Future deadline retained');
$check($map([],['schemaJobCountry'=>''])===null,'Missing physical location excluded');
$check($map(['schemaJobWorkplace'=>'remote'])===null,'Remote applicant countries required');
$remote=$map(['schemaJobWorkplace'=>'remote','schemaJobApplicantCountries'=>serialize(['DE','AT'])]);
$check($remote['jobLocationType']==='TELECOMMUTE' && !isset($remote['jobLocation']) && count($remote['applicantLocationRequirements'])===2,'Remote job geography');
$check(!isset($map(['schemaJobWorkplace'=>'hybrid'])['jobLocationType']),'Hybrid is not fully remote');
$check($mapper->map($record,$defaults,[],'https://example.org','de','Job','Description',$now)===null,'Missing employer excluded');
$check($mapper->map($record,$defaults,$employer,'https://example.org','de','Job',' ',$now)===null,'Missing description excluded');
$check(!isset($job['headline'],$job['articleBody'],$job['author']),'No article properties');
$entities = new VHUG\SchemaManagerBundle\Schema\EntityMapper();
$base=['entityId'=>'https://example.org/#entity','name'=>'Name','entityType'=>'Organization','legalName'=>'Legal','alternateName'=>'Alias','foundingDate'=>'1998'];
$org=$entities->map($base,null,null);
$check($org['foundingDate']==='1998' && $org['alternateName']==='Alias','Shared company facts');
$person=$entities->map(array_replace($base,['entityType'=>'Person','telephone'=>'+49 123','email'=>'public@example.org']),['jobTitle'=>'Berater'],null);
$check($person['telephone']==='+49 123' && $person['email']==='public@example.org' && !isset($person['legalName']),'Person public contact');
$service=$entities->map(array_replace($base,['entityType'=>'Service']),['serviceType'=>'Beratung','audienceType'=>'Mittelstand'],'https://example.org/service',$base);
$check($service['serviceType']==='Beratung' && $service['audience']['audienceType']==='Mittelstand','Localized service fields');
echo "PASS: 16 job and entity mapping checks.\n";
