services:
    _defaults:
        autowire: true
        autoconfigure: true
    VHUG\SchemaManagerBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,Model,SchemaManagerBundle.php}
    VHUG\SchemaManagerBundle\Backend\RelationshipMapModule:
        public: true
    VHUG\SchemaManagerBundle\Backend\AiHelperModule:
        public: true
